from Quiz6 import *
p1 = Point(1,2)
p2 = Point(4,8)
p3 = Point(3,5)
triangle = Triangle(point_1 = p1, point_2 = p2, point_3 = p3)
print(triangle.perimeter)
print(triangle.area)
print()
p0 = Point(0,0)
p3 = Point(0,4)
triangle.change_point_or_points(point_3 = p3, point_1 = p0)
print(p0.x, p0.y)
print(p3.x, p3.y)
print()
print(triangle.point_1.x,triangle.point_1.y)
print(triangle.point_2.x,triangle.point_2.y)
print(triangle.point_3.x,triangle.point_3.y)
print()
print(triangle.perimeter)
print(triangle.area)
triangle.change_point_or_points(point_2 = Point(4,0))
print()
print(triangle.perimeter)
print(triangle.area)